//! The `.nbc` (Nulang Bytecode) durable artifact format.
//!
//! A `.nbc` file is a frozen, versioned, content-addressable encoding of a
//! compiled [`crate::bytecode::CodeModule`]. It is the format a Nulang program
//! is *distributed* in: a `.nbc` minted in 2026 must load and run on any
//! conforming runtime in 2126 without the original source or compiler.
//!
//! # Byte layout (version 1; all integers big-endian)
//!
//! ```text
//! offset  size           field
//! 0       4              magic = b"NLBC"
//! 4       4              format_version (u32)
//! 8       4              language_version (u32)
//! 12      32             source_hash (blake3; 0x00..00 if unknown)
//! 44      4              instr_count (u32)
//! 48      4*instr_count  frozen-v1 instruction words (u32, BE)
//! 48+4n   4              meta_len (u32)
//! 52+4n   meta_len       JSON metadata
//! ```
//!
//! The byte-level implementation is intentionally isolated in the private
//! `nbc_v1` codec. Public callers keep using [`CodeModule::to_nbc`] and
//! [`CodeModule::from_nbc`]. This separation makes the published v1 codec,
//! rather than the live VM's future representation, carry the compatibility
//! obligation.
//!
//! New format versions must be additive and migrate through
//! [`crate::format::migrate`]; v1 bytes are never reinterpreted.

use crate::bytecode::CodeModule;
use crate::format::constants::FormatError;

/// A `.nbc` artifact decoded into memory, plus the provenance recorded in its
/// header.
#[derive(Debug, Clone)]
pub struct NbcArtifact {
    /// The decoded module.
    pub module: CodeModule,
    /// BLAKE3 hash of the originating source, if the header carried a non-zero
    /// hash. `None` when the artifact was emitted without source provenance.
    pub source_hash: Option<[u8; 32]>,
    /// The `.nbc` format version recorded in the header.
    pub format_version: u32,
    /// The Nulang language version recorded in the header.
    pub language_version: u32,
}

impl CodeModule {
    /// Serialize this module using the current published `.nbc` format.
    ///
    /// Version 1 encoding is delegated to the frozen `nbc_v1` codec so live
    /// runtime representation can evolve independently of the durable bytes.
    pub fn to_nbc(&self, source_hash: Option<[u8; 32]>) -> Result<Vec<u8>, FormatError> {
        super::nbc_v1::encode(self, source_hash)
    }

    /// Deserialize a `.nbc` byte slice into a module plus its recorded
    /// provenance.
    ///
    /// Version 1 decoding is delegated to the frozen `nbc_v1` codec. Future
    /// format dispatch belongs here while each version-specific byte layout
    /// remains isolated from the live VM representation.
    pub fn from_nbc(bytes: &[u8]) -> Result<NbcArtifact, FormatError> {
        super::nbc_v1::decode(bytes)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bytecode::{CodeModule, Constant, Instruction, OpCode};
    use crate::format::constants::{BYTECODE_VERSION, LANGUAGE_VERSION, NBC_HEADER_LEN};

    fn sample_module() -> CodeModule {
        let mut m = CodeModule::new("test");
        m.add_constant(Constant::Int(42));
        m.add_constant(Constant::String("hello".into()));
        m.emit(Instruction::new1(OpCode::ConstU, 0));
        m.emit(Instruction::new0(OpCode::Halt));
        m
    }

    #[test]
    fn golden_v1_bootstrap_artifact_remains_decodable() {
        // This is a real v1 artifact checked into the repository, not bytes
        // regenerated by today's encoder. If decoding this fixture breaks,
        // a frozen-format compatibility guarantee has regressed.
        let bytes = include_bytes!("../../bootstrap/compile_hex_host.nbc");
        let artifact = CodeModule::from_nbc(bytes).expect("historical v1 artifact must decode");

        assert_eq!(artifact.format_version, 1);
        assert_eq!(artifact.language_version, 1);
        // This particular historical bootstrap artifact was emitted without
        // source provenance, so the frozen all-zero hash decodes to None.
        assert_eq!(artifact.source_hash, None);

        assert_eq!(artifact.module.name, "main");
        assert_eq!(artifact.module.instructions.len(), 3493);
        assert_eq!(artifact.module.constants.len(), 73);
        assert_eq!(artifact.module.function_table.len(), 114);
        assert_eq!(artifact.module.entry_point, None);
    }

    #[test]
    fn test_nbc_roundtrip_preserves_module() {
        let m = sample_module();
        let bytes = m.to_nbc(None).expect("encode");
        let art = CodeModule::from_nbc(&bytes).expect("decode");
        assert_eq!(art.module, m, "round-trip must preserve the module");
        assert_eq!(art.format_version, BYTECODE_VERSION);
        assert_eq!(art.language_version, LANGUAGE_VERSION);
        assert!(art.source_hash.is_none(), "no source hash supplied");
    }

    #[test]
    fn test_nbc_roundtrip_with_source_hash() {
        let m = sample_module();
        let h = [0xAA; 32];
        let bytes = m.to_nbc(Some(h)).expect("encode");
        let art = CodeModule::from_nbc(&bytes).expect("decode");
        assert_eq!(art.source_hash, Some(h));
    }

    #[test]
    fn test_nbc_header_has_magic_and_version() {
        let bytes = sample_module().to_nbc(None).unwrap();
        assert_eq!(&bytes[0..4], b"NLBC");
        assert_eq!(u32::from_be_bytes(bytes[4..8].try_into().unwrap()), 1);
        assert_eq!(u32::from_be_bytes(bytes[8..12].try_into().unwrap()), 1);
    }

    #[test]
    fn test_nbc_rejects_truncated_header() {
        let err = CodeModule::from_nbc(&[0u8; 10]).unwrap_err();
        assert_eq!(
            err,
            FormatError::Truncated {
                need: NBC_HEADER_LEN,
                have: 10
            }
        );
    }

    #[test]
    fn test_nbc_rejects_bad_magic() {
        let mut bytes = sample_module().to_nbc(None).unwrap();
        bytes[0] = b'X';
        let err = CodeModule::from_nbc(&bytes).unwrap_err();
        assert!(matches!(err, FormatError::BadMagic { .. }));
    }

    #[test]
    fn test_nbc_rejects_unsupported_format_version() {
        let mut bytes = sample_module().to_nbc(None).unwrap();
        // Bump the format version field (offset 4) to a future version.
        bytes[4..8].copy_from_slice(&99u32.to_be_bytes());
        let err = CodeModule::from_nbc(&bytes).unwrap_err();
        assert!(matches!(
            err,
            FormatError::UnsupportedVersion { found: 99, .. }
        ));
    }

    #[test]
    fn test_nbc_rejects_incompatible_language_version() {
        let mut bytes = sample_module().to_nbc(None).unwrap();
        // Bump the language version field (offset 8) to a future version.
        bytes[8..12].copy_from_slice(&99u32.to_be_bytes());
        let err = CodeModule::from_nbc(&bytes).unwrap_err();
        assert!(matches!(
            err,
            FormatError::IncompatibleLanguage { artifact: 99, .. }
        ));
    }

    #[test]
    fn test_nbc_rejects_unknown_opcode_in_stream() {
        // Hand-craft a minimal artifact with an unknown opcode byte.
        let mut buf = Vec::new();
        buf.extend_from_slice(b"NLBC");
        buf.extend_from_slice(&1u32.to_be_bytes()); // format version
        buf.extend_from_slice(&1u32.to_be_bytes()); // language version
        buf.extend_from_slice(&[0u8; 32]); // source hash
        buf.extend_from_slice(&1u32.to_be_bytes()); // instr_count = 1
                                                    // One instruction with an unknown opcode 0xFE.
        let bad_instr: u32 = (0xFEu32 << 24) | 0;
        buf.extend_from_slice(&bad_instr.to_be_bytes());
        // Empty metadata body.
        let empty = CodeModule::new("x");
        let meta = serde_json::to_vec(&empty).unwrap();
        buf.extend_from_slice(&(meta.len() as u32).to_be_bytes());
        buf.extend_from_slice(&meta);
        let err = CodeModule::from_nbc(&buf).unwrap_err();
        assert!(matches!(err, FormatError::UnknownOpcode { opcode: 0xFE }));
    }

    #[test]
    fn test_nbc_rejects_non_finite_float_constant() {
        let mut m = sample_module();
        m.add_constant(Constant::Float(f64::NAN));
        let err = m.to_nbc(None).unwrap_err();
        assert!(matches!(err, FormatError::BadConstant(_)));
    }

    #[test]
    fn test_spawn_init_overrides_serde_default() {
        // A .nbc produced by an older build lacks `spawn_init_overrides`.
        // serde(default) must fill it with an empty Vec, not error.
        let json = r#"{
            "name": "test",
            "constants": [],
            "instructions": [],
            "behaviors": [],
            "function_table": [],
            "exports": [],
            "entry_point": null,
            "handler_tables": [],
            "actor_metadata": [],
            "foreign_functions": [],
            "tools": []
        }"#;
        let module: crate::bytecode::CodeModule =
            serde_json::from_str(json).expect("old-format .nbc metadata must deserialize");
        assert!(
            module.spawn_init_overrides.is_empty(),
            "missing field must default to empty Vec"
        );
        assert!(
            module.function_local_counts.is_empty(),
            "missing function_local_counts must default to empty Vec"
        );
    }
}
