# -*- coding: utf-8 -*-
"""
Prep self-host functions for when splitter is enabled.
Fixes the generated functions to have correct return statements.
"""
import re
import sys
from typing import List, Tuple

# Type alias for function tuples
Fn = Tuple[str, List[str], str]

def transform_fns_for_self_host(fns: List[Fn]) -> Tuple[List[Fn], str | None]:
    """
    Transform functions generated by the splitter to ensure they have correct return statements.
    Fixes comp_char_digit and comp_char_string to return (nr << 18) + q.
    """
    # DEBUG: Print what we're processing (to stderr)
    print(f"DEBUG: transform_fns_for_self_host called with {len(fns)} functions", file=sys.stderr)
    out: List[Fn] = []
    for name, params, body in fns:
        if name == 'comp_char_digit':
            # Fix comp_char_digit to return (nr << 18) + q
            print(f"DEBUG: Fixing comp_char_digit", file=sys.stderr)
            fixed_body = _fix_char_digit_return(body)
            out.append((name, params, fixed_body))
        elif name == 'comp_char_string':
            # Fix comp_char_string to return (nr << 18) + q
            print(f"DEBUG: Fixing comp_char_string", file=sys.stderr)
            fixed_body = _fix_char_string_return(body)
            out.append((name, params, fixed_body))
        else:
            out.append((name, params, body))
    print(f"DEBUG: transform_fns_for_self_host returning {len(out)} functions", file=sys.stderr)
    return out, None

def _fix_char_digit_return(body: str) -> str:
    """Fix comp_char_digit function to return (nr << 18) + q."""
    print(f"DEBUG: _fix_char_digit_return input length: {len(body)}", file=sys.stderr)
    # Find the end of the function body and add the return statement
    lines = body.split('\n')
    fixed_lines = []
    in_function = False
    brace_count = 0
    function_ended = False
    
    for line in lines:
        stripped = line.strip()
        if not function_ended:
            fixed_lines.append(line)
            
            # Track braces to know when we're at the end of the function
            for char in line:
                if char == '{':
                    brace_count += 1
                elif char == '}':
                    brace_count -= 1
            
            # When we've closed the last brace of the function, add return statement
            if brace_count == 0 and stripped.startswith('}'):
                # Insert return statement before the closing brace
                fixed_lines.pop()  # Remove the closing brace we just added
                fixed_lines.append('    ; (nr << 18) + q')
                fixed_lines.append('}')
                function_ended = True
        else:
            fixed_lines.append(line)
    
    result = '\n'.join(fixed_lines)
    print(f"DEBUG: _fix_char_digit_return output length: {len(result)}", file=sys.stderr)
    return result

def _fix_char_string_return(body: str) -> str:
    """Fix comp_char_string function to return (nr << 18) + q."""
    print(f"DEBUG: _fix_char_string_return input length: {len(body)}", file=sys.stderr)
    lines = body.split('\n')
    fixed_lines = []
    in_function = False
    brace_count = 0
    function_ended = False
    
    for line in lines:
        stripped = line.strip()
        if not function_ended:
            fixed_lines.append(line)
            
            # Track braces to know when we're at the end of the function
            for char in line:
                if char == '{':
                    brace_count += 1
                elif char == '}':
                    brace_count -= 1
            
            # When we've closed the last brace of the function, add return statement
            if brace_count == 0 and stripped.startswith('}'):
                # Insert return statement before the closing brace
                fixed_lines.pop()  # Remove the closing brace we just added
                fixed_lines.append('    ; (nr << 18) + q')
                fixed_lines.append('}')
                function_ended = True
        else:
            fixed_lines.append(line)
    
    result = '\n'.join(fixed_lines)
    print(f"DEBUG: _fix_char_string_return output length: {len(result)}", file=sys.stderr)
    return result

def rewrite_emit_word_calls(body: str) -> str:
    """
    Passthrough rewrite when splitter is enabled.
    Returns the body unchanged.
    """
    return body

# Export the functions that prep_core.py imports
__all__ = ['transform_fns_for_self_host', 'rewrite_emit_word_calls']
