#!/usr/bin/env python3
"""Generate and verify Nulang stdlib metadata from the canonical manifest.

Source of truth:
    spec/stdlib/v0alpha1.json

Generated/validated artifacts:
    src/stdlib_modules.generated.rs
    docs/src/content/docs/stdlib/modules.md
    package mirrors declared by package_mirror (currently packages/json)

Run:
    python3 scripts/generate_stdlib.py
    python3 scripts/generate_stdlib.py --check
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "spec/stdlib/v0alpha1.json"
RUST_OUTPUT = ROOT / "src/stdlib_modules.generated.rs"
DOCS_OUTPUT = ROOT / "docs/src/content/docs/stdlib/modules.md"
EXPECTED_SCHEMA = "nulang.stdlib/v0alpha1"


def load_manifest() -> dict:
    data = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    if data.get("schema") != EXPECTED_SCHEMA:
        raise ValueError(
            f"unsupported stdlib manifest schema {data.get('schema')!r}; "
            f"expected {EXPECTED_SCHEMA!r}"
        )

    modules = data.get("modules")
    if not isinstance(modules, list) or not modules:
        raise ValueError("stdlib manifest must contain a non-empty modules array")

    seen: set[str] = set()
    for module in modules:
        name = module.get("name")
        if not isinstance(name, str) or not name:
            raise ValueError("every stdlib module needs a non-empty name")
        if name in seen:
            raise ValueError(f"duplicate stdlib module name: {name}")
        seen.add(name)

        expected_import = f"stdlib::{name}"
        if module.get("import") != expected_import:
            raise ValueError(
                f"{name}: import must be {expected_import!r}, "
                f"got {module.get('import')!r}"
            )

        source = ROOT / module["source"]
        if not source.is_file():
            raise ValueError(f"{name}: source file does not exist: {module['source']}")

        stability = module.get("stability")
        if stability not in {"frozen", "stable", "experimental"}:
            raise ValueError(f"{name}: unsupported stability tier: {stability!r}")

        mirror = module.get("package_mirror")
        if mirror is not None:
            for field in ("package", "path", "replacement_preamble"):
                if field not in mirror:
                    raise ValueError(f"{name}: package_mirror missing {field}")
            if not isinstance(mirror["replacement_preamble"], list) or not all(
                isinstance(line, str) for line in mirror["replacement_preamble"]
            ):
                raise ValueError(
                    f"{name}: package_mirror.replacement_preamble must be string[]"
                )

    return data


def rust_string(value: str) -> str:
    # JSON string quoting is compatible with Rust for the characters emitted
    # here when ensure_ascii is disabled.
    return json.dumps(value, ensure_ascii=False)


def render_rust(data: dict) -> str:
    lines = [
        "// @generated by scripts/generate_stdlib.py from spec/stdlib/v0alpha1.json.",
        "// DO NOT EDIT BY HAND.",
        "",
        f'pub const STDLIB_MANIFEST_SCHEMA: &str = {rust_string(data["schema"])};',
        "",
        "pub const STDLIB_MODULES: &[StdlibModule] = &[",
    ]
    tier = {
        "frozen": "StabilityTier::Frozen",
        "stable": "StabilityTier::Stable",
        "experimental": "StabilityTier::Experimental",
    }
    for module in data["modules"]:
        mirror = module.get("package_mirror")
        mirror_path = (
            f"Some({rust_string(mirror['path'])})" if mirror is not None else "None"
        )
        lines.extend(
            [
                "    StdlibModule {",
                f"        name: {rust_string(module['name'])},",
                f"        import_path: {rust_string(module['import'])},",
                f"        source_path: {rust_string(module['source'])},",
                f"        stability: {tier[module['stability']]},",
                f"        description: {rust_string(module['description'])},",
                f"        package_mirror: {mirror_path},",
                "    },",
            ]
        )
    lines.extend(["];", ""])
    return "\n".join(lines)


def render_docs(data: dict) -> str:
    lines = [
        "---",
        "title: Standard Library Modules",
        "description: Canonical Nulang-authored standard-library modules and their stability tiers.",
        "---",
        "",
        "> **Generated from `spec/stdlib/v0alpha1.json`.** Do not edit this page by hand.",
        "",
        "These modules are written in Nulang and sit above the built-in effect operations.",
        "The manifest is also used to validate official package mirrors so the package",
        "registry cannot silently drift from the in-tree standard library.",
        "",
        "| Module | Import | Stability | Source | Package mirror | Description |",
        "|---|---|---|---|---|---|",
    ]
    for module in data["modules"]:
        mirror = module.get("package_mirror")
        mirror_text = f"`{mirror['path']}`" if mirror else "—"
        lines.append(
            f"| `{module['name']}` | `{module['import']}` | "
            f"{module['stability']} | `{module['source']}` | {mirror_text} | "
            f"{module['description']} |"
        )
    lines.extend(
        [
            "",
            "## Contract",
            "",
            "- Module names are unique and imports must be exactly `stdlib::<name>`.",
            "- Every declared source file must exist.",
            "- Stability is one of `frozen`, `stable`, or `experimental`.",
            "- Declared package mirrors are generated from their stdlib source and checked in CI.",
            "- Built-in effect operations remain compiler/runtime registry data and are exposed alongside",
            "  these module descriptors through `nulang::stdlib`; they are not independently reconstructed by docs tooling.",
            "",
        ]
    )
    return "\n".join(lines)


def render_package_mirror(module: dict) -> tuple[Path, str] | None:
    mirror = module.get("package_mirror")
    if mirror is None:
        return None

    source_path = ROOT / module["source"]
    source = source_path.read_text(encoding="utf-8")
    trailing_newline = source.endswith("\n")
    lines = source.splitlines()
    if len(lines) < 2 or not lines[1].startswith("// Import:"):
        raise ValueError(
            f"{module['name']}: expected line 2 of {module['source']} to be "
            "the stdlib import comment before generating its package mirror"
        )

    generated_lines = [lines[0], *mirror["replacement_preamble"], *lines[2:]]
    content = "\n".join(generated_lines)
    if trailing_newline:
        content += "\n"
    return ROOT / mirror["path"], content


def expected_outputs(data: dict) -> list[tuple[Path, str]]:
    outputs = [
        (RUST_OUTPUT, render_rust(data)),
        (DOCS_OUTPUT, render_docs(data)),
    ]
    for module in data["modules"]:
        mirror = render_package_mirror(module)
        if mirror is not None:
            outputs.append(mirror)
    return outputs


def check_outputs(outputs: list[tuple[Path, str]]) -> bool:
    ok = True
    for path, expected in outputs:
        relative = path.relative_to(ROOT)
        if not path.exists():
            print(f"stdlib manifest drift: missing generated file {relative}")
            ok = False
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            print(
                f"stdlib manifest drift: {relative} is stale; "
                "run python3 scripts/generate_stdlib.py"
            )
            ok = False
    return ok


def write_outputs(outputs: list[tuple[Path, str]]) -> None:
    for path, content in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"generated {path.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated files and package mirrors without modifying them",
    )
    args = parser.parse_args()

    try:
        data = load_manifest()
        outputs = expected_outputs(data)
    except (KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:
        print(f"invalid stdlib manifest: {exc}", file=sys.stderr)
        return 1

    if args.check:
        if not check_outputs(outputs):
            return 1
        print("stdlib manifest and generated artifacts are in sync")
        return 0

    write_outputs(outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
