from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f"{label}: expected source shape not found")
    return text.replace(old, new, 1)


runtime_path = Path("src/runtime/mod.rs")
runtime = runtime_path.read_text()

runtime = replace_once(
    runtime,
    """    /// Send a message to `target_id`'s `behavior` mailbox by name.\n    ///\n    /// KNOWN SURPRISING BEHAVIOR (verified 2026-08-02, not fixed --\n    /// see the comment in `flush_actor_mailbox` for why): a `behavior`\n    /// name that doesn't match any of the target's registered\n    /// behaviors resolves to behavior id 0 via `unwrap_or(0)` below,\n    /// NOT a dropped/no-op message -- a typo'd or undeclared behavior\n    /// name silently runs the actor's FIRST declared behavior instead\n    /// of erroring or being ignored. See SPEC2.md Chapter 8 (message\n    /// passing) and `conformance/behavior/lifecycle_03/04_*.nula`.\n""",
    """    /// Send a message to `target_id`'s `behavior` mailbox by name.\n    /// Unknown behavior names fail closed and are never aliases for behavior 0.\n""",
    "send_message docs",
)

runtime = replace_once(
    runtime,
    "        let behavior_id = self.behavior_id_for(target_id, behavior).unwrap_or(0);\n",
    """        let Some(behavior_id) = self.behavior_id_for(target_id, behavior) else {\n            warn!(\n                \"nulang-runtime: rejecting message to actor {}: unknown behavior '{}'\",\n                target_id, behavior\n            );\n            return;\n        };\n""",
    "send_message fallback",
)

runtime = replace_once(
    runtime,
    """        let behavior_idx = behavior_id as usize;\n\n        // Intercept semantic-memory behaviors generated by compile_agent.  These\n""",
    """        let behavior_idx = behavior_id as usize;\n        if !self.actor_has_behavior_id(actor_id, behavior_id) {\n            return Err(NuError::VMError {\n                msg: format!(\n                    \"actor {} does not declare behavior id {}\",\n                    actor_id, behavior_id\n                ),\n                span: Span::default(),\n            });\n        }\n\n        // Intercept semantic-memory behaviors generated by compile_agent.  These\n""",
    "ask guard",
)

runtime = replace_once(
    runtime,
    """            // A behavior_idx with neither a bytecode nor native handler\n            // falls through here silently. In practice this branch is\n            // unreachable for messages sent via `send_message`/\n            // `send_message_by_id` today: `send_message` resolves an\n            // unknown behavior NAME to id 0 via\n            // `behavior_id_for(..).unwrap_or(0)` (see its doc comment) --\n            // NOT a genuinely unknown numeric id -- so a typo'd or\n            // undeclared behavior name silently runs behavior 0 well\n            // before reaching this point, rather than being skipped as\n            // this comment used to claim. Tracked as a known surprising\n            // behavior in SPEC2.md (Chapter 8, message passing), not\n            // fixed here -- `send_message` is called pervasively and\n            // AGENTS.md documents the remote-message path as\n            // deliberately mirroring this same fallback, so correcting\n            // it needs a wider, carefully-audited change, not a\n            // single-site patch.\n""",
    """            // A numeric behavior id with neither a bytecode nor native handler\n            // falls through without executing a handler. Name-based sends are\n            // resolved fail-closed before enqueue; nominal numeric ownership is\n            // tightened separately by the actor-schema ownership work.\n""",
    "flush comment",
)

anchor = "    pub fn behavior_id_for(&self, target_id: u64, behavior: &str) -> Option<u16> {\n"
helper = """    /// Return whether `behavior_id` names a real native or bytecode handler on\n    /// `target_id`. This proves handler existence only; nominal actor-schema\n    /// ownership is enforced by the separate #270 runtime ownership slice.\n    fn actor_has_behavior_id(&self, target_id: u64, behavior_id: u16) -> bool {\n        let behavior_idx = behavior_id as usize;\n        let has_native = self\n            .actors\n            .get(&target_id)\n            .and_then(|actor| actor.behavior_table.get(behavior_idx))\n            .is_some_and(|entry| !entry.name.is_empty());\n        has_native || self.has_bytecode_handler(target_id, behavior_idx)\n    }\n\n"""
if "fn actor_has_behavior_id(&self" in runtime:
    raise SystemExit("actor_has_behavior_id already present")
runtime = replace_once(runtime, anchor, helper + anchor, "behavior helper anchor")
runtime_path.write_text(runtime)


distributed_path = Path("src/runtime/distributed.rs")
distributed = distributed_path.read_text()

distributed = replace_once(
    distributed,
    """                                    // Resolve behavior_id against the updated module\n                                    msg.behavior_id = runtime\n                                        .behavior_id_for(target_actor, &behavior_name)\n                                        .unwrap_or(0);\n""",
    """                                    // Resolve behavior id against the updated module.\n                                    // A successful fetch that still lacks the\n                                    // requested name is a failed delivery, not\n                                    // permission to execute behavior 0.\n                                    let Some(behavior_id) =\n                                        runtime.behavior_id_for(target_actor, &behavior_name)\n                                    else {\n                                        notify_delivery_failed(\n                                            runtime,\n                                            msg.sender,\n                                            \"unknown behavior after fetch\",\n                                        );\n                                        continue;\n                                    };\n                                    msg.behavior_id = behavior_id;\n""",
    "fetch retry",
)

distributed = replace_once(
    distributed,
    """                    // Resolve the behavior name against the target actor's\n                    // behavior table — the same rule local sends use\n                    // (`Runtime::send_message`). An unknown name falls back\n                    // to behavior 0, mirroring `send_message`'s\n                    // `unwrap_or(0)`.\n                    msg.behavior_id = runtime\n                        .behavior_id_for(target_actor, &behavior_name)\n                        .unwrap_or(0);\n""",
    """                    // Resolve the behavior name against the target actor's\n                    // behavior table. Unknown names must never alias behavior 0.\n                    // If a content hash is present, keep fetch-on-demand viable\n                    // with an invalid sentinel until the hash path loads the\n                    // missing implementation; the sentinel is never delivered.\n                    match runtime.behavior_id_for(target_actor, &behavior_name) {\n                        Some(behavior_id) => msg.behavior_id = behavior_id,\n                        None if content_hash.is_some() => msg.behavior_id = u16::MAX,\n                        None => {\n                            warn!(\n                                \"nulang-net: rejecting message to actor {}: unknown behavior '{}'\",\n                                target_actor, behavior_name\n                            );\n                            notify_delivery_failed(runtime, msg.sender, \"unknown behavior\");\n                            ack_packet(transport, cluster, incoming.from_node, incoming.seq);\n                            continue;\n                        }\n                    }\n""",
    "remote resolution",
)

distributed = replace_once(
    distributed,
    """                                // Retry resolution after hot-reload\n                                msg.behavior_id = runtime\n                                    .behavior_id_for(target_actor, &behavior_name)\n                                    .unwrap_or(0);\n""",
    """                                // Retry resolution after hot-reload. A fetched\n                                // module that still does not declare the name is\n                                // rejected rather than redirected to behavior 0.\n                                let Some(behavior_id) =\n                                    runtime.behavior_id_for(target_actor, &behavior_name)\n                                else {\n                                    notify_delivery_failed(\n                                        runtime,\n                                        msg.sender,\n                                        \"unknown behavior after hot reload\",\n                                    );\n                                    ack_packet(\n                                        transport,\n                                        cluster,\n                                        incoming.from_node,\n                                        incoming.seq,\n                                    );\n                                    continue;\n                                };\n                                msg.behavior_id = behavior_id;\n""",
    "hot reload retry",
)

distributed = replace_once(
    distributed,
    """        // Unknown behavior name: falls back to behavior 0, mirroring\n        // `Runtime::send_message`'s `unwrap_or(0)` for local sends.\n""",
    """        // Unknown behavior name: must be rejected without enqueuing\n        // or executing any target handler.\n""",
    "remote test docs",
)

distributed = replace_once(
    distributed,
    """        assert_eq!(\n            count, 4,\n            \"unknown behavior name must fall back to behavior 0 (\\\"dec\\\")\"\n        );\n""",
    """        assert_eq!(\n            count, 5,\n            \"unknown behavior name must leave target state unchanged\"\n        );\n""",
    "remote test assertion",
)
distributed_path.write_text(distributed)


tests_path = Path("src/runtime/tests.rs")
tests = tests_path.read_text()
if "fn p0_unknown_named_send_is_rejected()" in tests:
    raise SystemExit("focused P0 tests already present")
tests += r'''

#[test]
fn p0_unknown_named_send_is_rejected() {
    fn increment(actor: &mut Actor, _args: &[Value]) {
        let n = actor
            .get_state_field("count")
            .and_then(|v| v.as_int())
            .unwrap_or(0);
        actor.set_state_field("count", Value::int(n + 1));
    }

    let mut rt = Runtime::new();
    let actor_id = rt.spawn_actor(Box::new(|| vec![("count".to_string(), Value::int(0))]));
    rt.actors
        .get_mut(&actor_id)
        .unwrap()
        .register_behavior("first", increment);

    rt.send_message(actor_id, "does_not_exist", &[]);
    assert!(rt.actors.get(&actor_id).unwrap().mailbox.is_empty());
    rt.run_scheduler();
    assert_eq!(
        rt.actors
            .get(&actor_id)
            .unwrap()
            .get_state_field("count")
            .and_then(|v| v.as_int()),
        Some(0)
    );

    rt.send_message(actor_id, "first", &[]);
    rt.run_scheduler();
    assert_eq!(
        rt.actors
            .get(&actor_id)
            .unwrap()
            .get_state_field("count")
            .and_then(|v| v.as_int()),
        Some(1)
    );
}

#[test]
fn p0_unknown_numeric_ask_is_rejected_without_running_behavior_zero() {
    fn increment(actor: &mut Actor, _args: &[Value]) {
        let n = actor
            .get_state_field("count")
            .and_then(|v| v.as_int())
            .unwrap_or(0);
        actor.set_state_field("count", Value::int(n + 1));
    }

    let mut rt = Runtime::new();
    let actor_id = rt.spawn_actor(Box::new(|| vec![("count".to_string(), Value::int(0))]));
    rt.actors
        .get_mut(&actor_id)
        .unwrap()
        .register_behavior("first", increment);

    let result = rt.ask_actor_sync(actor_id, u16::MAX, &[]);
    assert!(result.is_err(), "invalid numeric ask must fail closed");
    assert_eq!(
        rt.actors
            .get(&actor_id)
            .unwrap()
            .get_state_field("count")
            .and_then(|v| v.as_int()),
        Some(0),
        "invalid numeric ask must not execute behavior 0"
    );
}
'''
tests_path.write_text(tests)


# Preserve fail-closed name semantics across the shard boundary. A sender
# shard may know the target actor id but cannot inspect the owning shard's
# behavior table, so name-based sends must carry the name and resolve it only
# after the message reaches the owner shard.
runtime = runtime_path.read_text()

runtime = replace_once(
    runtime,
    """        let Some(behavior_id) = self.behavior_id_for(target_id, behavior) else {
            warn!(
                "nulang-runtime: rejecting message to actor {}: unknown behavior '{}'",
                target_id, behavior
            );
            return;
        };
        self.send_message_by_id(target_id, behavior_id, args);
""",
    """        if !self.actors.contains_key(&target_id) && self.shard_count > 1 {
            let target_shard = (target_id % self.shard_count as u64) as u16;
            if target_shard != self.shard_idx {
                self.send_cross_shard_named_message(target_id, behavior, args);
                return;
            }
        }
        let Some(behavior_id) = self.behavior_id_for(target_id, behavior) else {
            warn!(
                "nulang-runtime: rejecting message to actor {}: unknown behavior '{}'",
                target_id, behavior
            );
            return;
        };
        self.send_message_by_id(target_id, behavior_id, args);
""",
    "cross-shard named send routing",
)

runtime = replace_once(
    runtime,
    """    DeliverMessage {
        target_id: u64,
        behavior_id: u16,
        payload: Vec<Value>,
""",
    """    DeliverMessage {
        target_id: u64,
        behavior_id: Option<u16>,
        behavior_name: Option<String>,
        payload: Vec<Value>,
""",
    "cross-shard value message identity",
)

runtime = replace_once(
    runtime,
    """    DeliverMessageWithObjects {
        target_id: u64,
        behavior_id: u16,
        payload: Vec<Value>,
""",
    """    DeliverMessageWithObjects {
        target_id: u64,
        behavior_id: Option<u16>,
        behavior_name: Option<String>,
        payload: Vec<Value>,
""",
    "cross-shard object message identity",
)

runtime = replace_once(
    runtime,
    """            let _ = tx[target_shard as usize].try_send(CrossShardMsg::DeliverMessage {
                target_id,
                behavior_id,
                payload: args,
""",
    """            let _ = tx[target_shard as usize].try_send(CrossShardMsg::DeliverMessage {
                target_id,
                behavior_id: Some(behavior_id),
                behavior_name: None,
                payload: args,
""",
    "numeric cross-shard value constructor",
)

runtime = replace_once(
    runtime,
    """            let _ = tx[target_shard as usize].try_send(CrossShardMsg::DeliverMessageWithObjects {
                target_id,
                behavior_id,
                payload: args,
""",
    """            let _ = tx[target_shard as usize].try_send(CrossShardMsg::DeliverMessageWithObjects {
                target_id,
                behavior_id: Some(behavior_id),
                behavior_name: None,
                payload: args,
""",
    "numeric cross-shard object constructor",
)

named_helper = r'''
    /// Send a name-based message to another shard without inventing a numeric
    /// behavior id. The owning shard resolves the name against the target
    /// actor after any required grain hydration and fails closed if absent.
    fn send_cross_shard_named_message(
        &mut self,
        target_id: u64,
        behavior_name: &str,
        args: &[Value],
    ) -> bool {
        let target_shard = (target_id % self.shard_count as u64) as u16;
        for arg in args {
            if arg.is_ptr() || arg.is_actor_ref() || arg.is_closure() {
                tracing::warn!(
                    "nulang-shard: dropping named cross-shard message to actor {}: \
                     payload contains heap pointer / actor ref / closure",
                    target_id
                );
                return false;
            }
        }
        let tx = self.cross_shard_tx.as_ref().unwrap();
        let out_trace = self.current_trace.as_ref().map(|t| t.to_traceparent());
        let object_refs: Vec<crate::runtime::object_store::ObjectId> =
            args.iter().filter_map(|v| v.as_object_id()).collect();
        if object_refs.is_empty() {
            let _ = tx[target_shard as usize].try_send(CrossShardMsg::DeliverMessage {
                target_id,
                behavior_id: None,
                behavior_name: Some(behavior_name.to_string()),
                payload: args.to_vec(),
                sender: self.current_actor.unwrap_or(0),
                trace_id: out_trace,
                grain_id: None,
            });
        } else {
            let mut objects = Vec::with_capacity(object_refs.len());
            for id in object_refs {
                if let Some(entry) = self.object_store.get(id) {
                    objects.push((id, entry.as_bytes().to_vec()));
                }
            }
            let _ =
                tx[target_shard as usize].try_send(CrossShardMsg::DeliverMessageWithObjects {
                    target_id,
                    behavior_id: None,
                    behavior_name: Some(behavior_name.to_string()),
                    payload: args.to_vec(),
                    objects,
                    sender: self.current_actor.unwrap_or(0),
                    trace_id: out_trace,
                    grain_id: None,
                });
        }
        true
    }

'''
runtime = replace_once(
    runtime,
    """    /// Send a message to a virtual actor (grain) identified by its stable
""",
    named_helper + """    /// Send a message to a virtual actor (grain) identified by its stable
""",
    "named cross-shard helper anchor",
)

runtime = replace_once(
    runtime,
    """    fn deliver_cross_shard_message(
        &mut self,
        target_id: u64,
        behavior_id: u16,
        payload: Vec<Value>,
        sender: u64,
        trace_id: Option<String>,
        grain_id: Option<GrainId>,
    ) {
""",
    """    fn deliver_cross_shard_message(
        &mut self,
        target_id: u64,
        behavior_id: Option<u16>,
        behavior_name: Option<String>,
        payload: Vec<Value>,
        sender: u64,
        trace_id: Option<String>,
        grain_id: Option<GrainId>,
    ) {
        let dlq_behavior_id = behavior_id.unwrap_or(0);
""",
    "cross-shard delivery identity signature",
)

runtime = replace_once(
    runtime,
    """                        &Message {
                            behavior_id,
                            payload: Arc::new(Vec::new()),
                            sender,
                            priority: MessagePriority::System,
                            trace_id: None,
                        },
                        "grain hydration failed (cross-shard)",
""",
    """                        &Message {
                            behavior_id: dlq_behavior_id,
                            payload: Arc::new(Vec::new()),
                            sender,
                            priority: MessagePriority::System,
                            trace_id: None,
                        },
                        "grain hydration failed (cross-shard)",
""",
    "cross-shard hydration dlq identity",
)

resolution = r'''
        let behavior_id = match (behavior_id, behavior_name.as_deref()) {
            (Some(behavior_id), None) => behavior_id,
            (None, Some(behavior_name)) => {
                let Some(behavior_id) = self.behavior_id_for(target_id, behavior_name) else {
                    warn!(
                        "nulang-shard: rejecting message to actor {}: unknown behavior '{}'",
                        target_id, behavior_name
                    );
                    self.route_to_dlq(
                        &Message {
                            behavior_id: 0,
                            payload: Arc::new(Vec::new()),
                            sender,
                            priority: MessagePriority::System,
                            trace_id: None,
                        },
                        "unknown behavior (cross-shard)",
                    );
                    return;
                };
                behavior_id
            }
            _ => {
                warn!(
                    "nulang-shard: rejecting malformed cross-shard behavior identity for actor {}",
                    target_id
                );
                self.route_to_dlq(
                    &Message {
                        behavior_id: 0,
                        payload: Arc::new(Vec::new()),
                        sender,
                        priority: MessagePriority::System,
                        trace_id: None,
                    },
                    "invalid behavior identity (cross-shard)",
                );
                return;
            }
        };

'''
runtime = replace_once(
    runtime,
    """        let msg = Message {
            behavior_id,
            payload: Arc::new(payload),
""",
    resolution + """        let msg = Message {
            behavior_id,
            payload: Arc::new(payload),
""",
    "cross-shard name resolution before mailbox",
)

runtime = replace_once(
    runtime,
    """                CrossShardMsg::DeliverMessage {
                    target_id,
                    behavior_id,
                    payload,
                    sender,
                    trace_id,
                    grain_id,
                } => {
                    self.deliver_cross_shard_message(
                        target_id,
                        behavior_id,
                        payload,
""",
    """                CrossShardMsg::DeliverMessage {
                    target_id,
                    behavior_id,
                    behavior_name,
                    payload,
                    sender,
                    trace_id,
                    grain_id,
                } => {
                    self.deliver_cross_shard_message(
                        target_id,
                        behavior_id,
                        behavior_name,
                        payload,
""",
    "drain named cross-shard value message",
)

runtime = replace_once(
    runtime,
    """                CrossShardMsg::DeliverMessageWithObjects {
                    target_id,
                    behavior_id,
                    mut payload,
                    objects,
                    sender,
                    trace_id,
                    grain_id,
                } => {
""",
    """                CrossShardMsg::DeliverMessageWithObjects {
                    target_id,
                    behavior_id,
                    behavior_name,
                    mut payload,
                    objects,
                    sender,
                    trace_id,
                    grain_id,
                } => {
""",
    "drain named cross-shard object pattern",
)

runtime = replace_once(
    runtime,
    """                    self.deliver_cross_shard_message(
                        target_id,
                        behavior_id,
                        payload,
                        sender,
                        trace_id,
                        grain_id,
                    );
""",
    """                    self.deliver_cross_shard_message(
                        target_id,
                        behavior_id,
                        behavior_name,
                        payload,
                        sender,
                        trace_id,
                        grain_id,
                    );
""",
    "drain named cross-shard object delivery",
)

runtime_path.write_text(runtime)
