//! High-level Intermediate Representation (HIR).
//!
//! HIR is the output of type checking and effect/capability analysis.
//! It mirrors the AST but:
//!   - every binding and operand carries a resolved `Type`;
//!   - nested expressions are flattened into statements/terminators;
//!   - actor/module structure is preserved;
//!   - patterns are preserved with type annotations.

use crate::ast::{BinOp, CrdtType, Expr, Literal, Pattern, StateModel, UnOp};
use crate::types::{Capability, EffectRow, Span, Type};

// Re-exported AST types used in HIR declarations
pub use crate::ast::{DatabaseColumn, DatabaseTable};

// ---------------------------------------------------------------------------
// Module and declarations
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
pub struct Module {
    pub name: String,
    pub decls: Vec<Decl>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Decl {
    Function(FunctionDef),
    Actor(ActorDef),
    TypeAlias {
        name: String,
        type_params: Vec<String>,
        body: Type,
        opaque: bool,
        public: bool,
        span: Span,
    },
    RecordType {
        name: String,
        type_params: Vec<String>,
        fields: Vec<(String, Type)>,
        public: bool,
        span: Span,
    },
    VariantType {
        name: String,
        type_params: Vec<String>,
        variants: Vec<(String, Option<Type>)>,
        public: bool,
        span: Span,
    },
    EffectDecl {
        name: String,
        ops: Vec<(String, Vec<Type>, Type)>,
        span: Span,
    },
    Module {
        name: String,
        exports: Vec<String>,
        decls: Vec<Decl>,
        span: Span,
    },
    Import {
        path: String,
        items: Vec<String>,
        span: Span,
    },
    Database {
        name: String,
        tables: Vec<DatabaseTable>,
        span: Span,
    },
    ExternBlock {
        library: String,
        funcs: Vec<ExternFunc>,
        span: Span,
    },
    Workflow {
        name: String,
        span: Span,
    },
    Agent {
        name: String,
        span: Span,
    },
    Constant {
        name: String,
        body: Body,
        span: Span,
    },
    CrdtDecl {
        name: String,
        fields: Vec<(String, CrdtType, Type, Expr)>,
        span: Span,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub struct FunctionDef {
    pub name: String,
    pub type_params: Vec<String>,
    pub params: Vec<(String, Type)>,
    pub dict_params: Vec<(String, Type)>,
    pub ret: Type,
    pub effect: EffectRow,
    pub cap: Capability,
    pub body: Body,
    pub public: bool,
    /// Web framework compile-time placement hint (None = infer from effect row).
    pub placement: Option<crate::types::Placement>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ActorDef {
    pub name: String,
    pub type_params: Vec<String>,
    pub persistent: bool,
    pub state_fields: Vec<(String, StateModel, Type, Operand)>,
    pub behaviors: Vec<BehaviorDef>,
    pub init: Vec<(String, Operand)>,
    /// Typed event declarations from an `events` block (entity only).
    pub events: Vec<crate::ast::EventDecl>,
    /// Apply handlers from an `apply` block (entity only).
    pub apply_handlers: Vec<crate::ast::ApplyHandler>,
    /// Entity schema version (defaults to 1).  RFC 0008.
    pub version: u32,
    pub migrations: Vec<crate::ast::MigrationDecl>,
    /// True if this actor was generated from an `organization` declaration (RFC 0009).
    pub is_organization: bool,
    /// True if this actor was generated by desugaring a `workflow`
    /// declaration. The runtime uses this to intercept step dispatch.
    pub is_workflow: bool,
    /// True if this actor was generated by desugaring an `agent`
    /// declaration. The runtime uses this (plus `semantic_memory_dimensions`
    /// / `procedural_memory_namespace`) to intercept the generated
    /// memory-behavior names and implement them directly instead of running
    /// their placeholder bytecode bodies.
    pub is_agent: bool,
    /// True if declared as `virtual entity` (RFC 0016 virtual actor
    /// auto-hydration).
    pub virtual_: bool,
    pub tools: Vec<crate::tool_schema::ToolSchema>,
    pub semantic_memory_dimensions: Option<usize>,
    pub procedural_memory_namespace: Option<String>,
    /// Serialized fallback configuration (JSON `Vec<AgentFallbackEntry>`).
    pub fallback_config: String,
    /// Serialized retry configuration (JSON `Option<AgentRetryConfig>`).
    pub retry_config: String,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct BehaviorDef {
    pub name: String,
    pub params: Vec<(String, Type)>,
    pub ret: Type,
    pub effect: EffectRow,
    pub cap: Capability,
    pub body: Body,
    /// Saga compensation body for a `workflow` step, run in reverse order if
    /// a later step fails. `None` for ordinary (non-workflow) behaviors.
    pub compensate: Option<Body>,
    /// Branch names for a step synthesized from a `parallel { ... }` block
    /// (see `hir_lower::desugar_workflow`). `None` for an ordinary step; the
    /// runtime uses this to skip branches a crash already completed.
    pub parallel_branches: Option<Vec<String>>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ExternFunc {
    pub name: String,
    pub params: Vec<(String, Type)>,
    pub ret: Type,
    pub span: Span,
}

// ---------------------------------------------------------------------------
// Body: statements + terminator
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
pub struct Body {
    pub stmts: Vec<Stmt>,
    pub terminator: Terminator,
}

impl Default for Body {
    fn default() -> Self {
        Body {
            stmts: Vec::new(),
            terminator: Terminator::Yield(Operand::Unit),
        }
    }
}

impl Body {
    pub fn is_terminated(&self) -> bool {
        matches!(
            self.terminator,
            Terminator::FnReturn(_) | Terminator::Break(_)
        )
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum Stmt {
    Let {
        name: String,
        ty: Type,
        value: RValue,
        span: Span,
    },
    Assign {
        target: Place,
        value: RValue,
        span: Span,
    },
    StateSet {
        field: String,
        value: Operand,
        span: Span,
    },
    Emit {
        event: String,
        args: Vec<Operand>,
        span: Span,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum Place {
    Var(String, Type),
    Field {
        base: Box<Place>,
        field: String,
        ty: Type,
    },
    Index {
        base: Box<Place>,
        idx: Operand,
        ty: Type,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum RValue {
    Use(Operand),
    /// Runtime panic with a message (contract violations).
    Panic(String),
    Literal(Literal, Type),
    Binary(BinOp, Operand, Operand, Type),
    Unary(UnOp, Operand, Type),
    Call {
        func: Operand,
        args: Vec<Operand>,
        ty: Type,
    },
    Closure {
        params: Vec<(String, Type)>,
        body: Box<Body>,
        captures: Vec<String>,
        ty: Type,
    },
    /// A recursive function binding (`let rec f = ...` / self-referencing
    /// let-bound lambda). Unlike `Closure`, `name` is in scope inside `body`.
    RecClosure {
        name: String,
        params: Vec<(String, Type)>,
        body: Box<Body>,
        ty: Type,
    },
    Tuple(Vec<Operand>, Type),
    Record(Vec<(String, Operand)>, Type),
    /// Record update: { base .. field = val, ... }. Creates a shallow copy
    /// of `base` with the listed field overrides applied.
    RecordUpdate {
        base: Operand,
        overrides: Vec<(String, Operand)>,
        ty: Type,
    },
    Array(Vec<Operand>, Type),
    FieldAccess {
        base: Operand,
        field: String,
        ty: Type,
    },
    Index {
        base: Operand,
        idx: Operand,
        ty: Type,
    },
    /// Expression-position conditional. Each branch body yields its value via
    /// a `Yield` terminator; the whole rvalue evaluates to that value.
    If {
        cond: Operand,
        then_body: Box<Body>,
        else_body: Option<Box<Body>>,
        ty: Type,
    },
    /// Expression-position match. Arm bodies yield their value via `Yield`.
    /// Each arm is `(pattern, optional guard body, arm body)`; the guard
    /// body yields a boolean and is evaluated with the pattern's bindings
    /// in scope after the pattern test passes.
    Match {
        scrutinee: Operand,
        arms: Vec<(Pattern, Option<Box<Body>>, Box<Body>)>,
        ty: Type,
    },
    /// Array iteration loop; evaluates to unit.
    For {
        var: String,
        iterable: Operand,
        body: Box<Body>,
    },
    /// While loop: cond { body }; evaluates to unit.
    While {
        cond: Box<Body>,
        body: Box<Body>,
        span: Span,
    },
    /// Scoped block: evaluates `body` in a fresh scope so that bindings
    /// inside `body` do not leak to the surrounding expression. The body
    /// yields its result via a `Yield` terminator.
    Block(Box<Body>),
    Spawn {
        actor_type: String,
        init: Vec<(String, Operand)>,
        /// Remote spawn target (`spawn@node_expr Foo(...)`); `None` = local.
        target_node: Option<Operand>,
        /// Spawn-time capability grant tokens (e.g. `Net::TcpOut(h:p)`).
        capabilities: Vec<String>,
        ty: Type,
    },
    Send {
        actor: Operand,
        behavior: String,
        args: Vec<Operand>,
        remote: bool,
        ty: Type,
    },
    Ask {
        actor: Operand,
        behavior: String,
        args: Vec<Operand>,
        remote: bool,
        timeout_ms: Option<u64>,
        ty: Type,
    },
    SelfRef(Type),
    Perform {
        effect: String,
        op: String,
        args: Vec<Operand>,
        ty: Type,
    },
    /// Resume a suspended effect continuation with a value.
    Resume {
        value: Operand,
        ty: Type,
    },
    Handle {
        body: Box<Body>,
        handlers: Vec<EffectHandler>,
        ty: Type,
    },
    Receive {
        arms: Vec<(String, Vec<Pattern>, Option<Box<Body>>, Box<Body>)>,
        /// Optional `after ms => body` clause: `(timeout_ms, timeout_body)`.
        after: Option<(Box<Body>, Box<Body>)>,
        ty: Type,
    },
    Migrate {
        actor: Operand,
        node: Operand,
        ty: Type,
    },
    CapCheck {
        operand: Operand,
        required: Capability,
    },
    FFICall {
        symbol: String,
        args: Vec<Operand>,
        ty: Type,
    },
    // AI runtime builtins (Pipeline, Supervisor, Debate)
    PipelineNew {
        ty: Type,
    },
    PipelineStage {
        id: Operand,
        name: Operand,
        actor: Operand,
        template: Operand,
        ty: Type,
    },
    PipelineRun {
        id: Operand,
        input: Operand,
        ty: Type,
    },
    SupervisorNew {
        ty: Type,
    },
    SupervisorWorker {
        id: Operand,
        name: Operand,
        actor: Operand,
        description: Operand,
        ty: Type,
    },
    SupervisorRun {
        id: Operand,
        task: Operand,
        ty: Type,
    },
    DebateNew {
        topic: Operand,
        rounds: Operand,
        threshold: Operand,
        ty: Type,
    },
    DebateParticipant {
        id: Operand,
        name: Operand,
        stance: Operand,
        actor: Operand,
        ty: Type,
    },
    DebateRun {
        id: Operand,
        ty: Type,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum Terminator {
    /// The body evaluates to this operand and control continues in the
    /// enclosing context (function return for a top-level body, join block
    /// for branch/arm/handler bodies). Synthesized by lowering.
    Yield(Operand),
    /// An explicit `return` expression: always returns from the enclosing
    /// function, even inside a branch or loop body.
    FnReturn(Option<Operand>),
    /// An explicit `break` expression: exits the innermost loop.
    Break(Option<Operand>),
}

#[derive(Debug, Clone, PartialEq)]
pub struct EffectHandler {
    pub effect_name: String,
    pub op_name: String,
    pub params: Vec<(String, Type)>,
    pub resume: bool,
    pub body: Box<Body>,
    pub span: Span,
}

// ---------------------------------------------------------------------------
// Operands
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
pub enum Operand {
    Var(String, Type),
    Literal(Literal, Type),
    Unit,
}

impl Operand {
    pub fn ty(&self) -> Type {
        match self {
            Operand::Var(_, ty) => ty.clone(),
            Operand::Literal(_, ty) => ty.clone(),
            Operand::Unit => Type::unit(),
        }
    }
}

impl Place {
    pub fn ty(&self) -> Type {
        match self {
            Place::Var(_, ty) => ty.clone(),
            Place::Field { ty, .. } => ty.clone(),
            Place::Index { ty, .. } => ty.clone(),
        }
    }
}

impl RValue {
    pub fn ty(&self) -> Type {
        match self {
            RValue::Use(op) => op.ty(),
            RValue::Panic(_) => Type::unit(),
            RValue::Literal(_, ty) => ty.clone(),
            RValue::Binary(_, _, _, ty) => ty.clone(),
            RValue::Unary(_, _, ty) => ty.clone(),
            RValue::Call { ty, .. } => ty.clone(),
            RValue::Closure { ty, .. } => ty.clone(),
            RValue::RecClosure { ty, .. } => ty.clone(),
            RValue::Tuple(_, ty) => ty.clone(),
            RValue::Record(_, ty) => ty.clone(),
            RValue::RecordUpdate { ty, .. } => ty.clone(),
            RValue::Array(_, ty) => ty.clone(),
            RValue::FieldAccess { ty, .. } => ty.clone(),
            RValue::Index { ty, .. } => ty.clone(),
            RValue::If { ty, .. } => ty.clone(),
            RValue::Match { ty, .. } => ty.clone(),
            RValue::For { .. } => Type::unit(),
            RValue::While { .. } => Type::unit(),
            RValue::Block(..) => Type::unit(),
            RValue::Spawn { ty, .. } => ty.clone(),
            RValue::Send { ty, .. } => ty.clone(),
            RValue::Ask { ty, .. } => ty.clone(),
            RValue::SelfRef(ty) => ty.clone(),
            RValue::Perform { ty, .. } => ty.clone(),
            RValue::Resume { ty, .. } => ty.clone(),
            RValue::Handle { ty, .. } => ty.clone(),
            RValue::Receive { ty, .. } => ty.clone(),
            RValue::Migrate { ty, .. } => ty.clone(),
            RValue::CapCheck { .. } => Type::bool(),
            RValue::FFICall { ty, .. } => ty.clone(),
            RValue::PipelineNew { ty } => ty.clone(),
            RValue::PipelineStage { ty, .. } => ty.clone(),
            RValue::PipelineRun { ty, .. } => ty.clone(),
            RValue::SupervisorNew { ty } => ty.clone(),
            RValue::SupervisorWorker { ty, .. } => ty.clone(),
            RValue::SupervisorRun { ty, .. } => ty.clone(),
            RValue::DebateNew { ty, .. } => ty.clone(),
            RValue::DebateParticipant { ty, .. } => ty.clone(),
            RValue::DebateRun { ty, .. } => ty.clone(),
        }
    }
}

// ---------------------------------------------------------------------------
// Builder helpers
// ---------------------------------------------------------------------------

impl Body {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn with_terminator(terminator: Terminator) -> Self {
        Self {
            stmts: Vec::new(),
            terminator,
        }
    }

    pub fn push(&mut self, stmt: Stmt) {
        self.stmts.push(stmt);
    }

    pub fn set_terminator(&mut self, terminator: Terminator) {
        self.terminator = terminator;
    }
}

impl Module {
    pub fn new(name: impl Into<String>) -> Self {
        Module {
            name: name.into(),
            decls: Vec::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::Literal;

    #[test]
    fn test_body_default() {
        let body = Body::default();
        assert!(body.stmts.is_empty());
        assert_eq!(body.terminator, Terminator::Yield(Operand::Unit));
    }

    #[test]
    fn test_body_push_stmt() {
        let mut body = Body::new();
        let stmt = Stmt::Let {
            name: "x".into(),
            ty: Type::int(),
            value: RValue::Use(Operand::Literal(Literal::Int(42), Type::int())),
            span: Span::default(),
        };
        body.push(stmt.clone());
        assert_eq!(body.stmts.len(), 1);
        assert_eq!(body.stmts[0], stmt);
    }

    #[test]
    fn test_body_set_terminator() {
        let mut body = Body::new();
        body.set_terminator(Terminator::FnReturn(Some(Operand::Unit)));
        assert_eq!(body.terminator, Terminator::FnReturn(Some(Operand::Unit)));
    }

    #[test]
    fn test_operand_variants() {
        let _ = Operand::Var("x".into(), Type::int());
        let _ = Operand::Literal(Literal::Int(42), Type::int());
        let _ = Operand::Unit;
    }

    #[test]
    fn test_module_new() {
        let m = Module::new("test");
        assert_eq!(m.name, "test");
        assert!(m.decls.is_empty());
    }

    #[test]
    fn test_function_def_new() {
        let def = FunctionDef {
            name: "f".into(),
            type_params: vec![],
            params: vec![],
            dict_params: vec![],
            ret: Type::unit(),
            effect: EffectRow::empty(),
            cap: Capability::Ref,
            body: Body::default(),
            public: true,
            placement: None,
            span: Span::default(),
        };
        assert_eq!(def.name, "f");
    }

    #[test]
    fn test_actor_def_new() {
        let def = ActorDef {
            name: "a".into(),
            type_params: vec![],
            persistent: false,
            state_fields: vec![],
            behaviors: vec![],
            init: vec![],
            events: vec![],
            apply_handlers: vec![],
            version: 1,
            migrations: vec![],
            is_workflow: false,
            is_organization: false,
            is_agent: false,
            virtual_: false,
            tools: vec![],
            semantic_memory_dimensions: None,
            procedural_memory_namespace: None,
            fallback_config: String::new(),
            retry_config: String::new(),
            span: Span::default(),
        };
        assert_eq!(def.name, "a");
    }
}
