name: Lockfile Temp

on:
  pull_request:
    branches:
      - perf/faster-rust-builds

permissions:
  contents: read

jobs:
  generate-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - name: Generate Cargo.lock
        run: cargo generate-lockfile
      - name: Upload Cargo.lock
        uses: actions/upload-artifact@v4
        with:
          name: cargo-lock
          path: Cargo.lock
          if-no-files-found: error
